data_path: /Users/jgreco/local-io/LBT-2018B/data/reduced-10-23

mods_channel: blue

arc_lamp: argon

sources:
    name: G191
    nexp: 3
    stack_func: mean

standards: 
    name: Feige110
    nexp: ~
    stack_func: median
    sampling: 50 # angstrom
    calibrate_star_idx: 0

pipeline_steps:
    identify: False
    reidentify: False
    fitcoords: False
    transform: False
    background: False
    stack: False
    extinction: False
    apall: True
    standard_star: False
    calibrate: True

identify_params: 

reidentify_params: 

fitcoords_params:

transform_params: 

background_params: 

apall_params: 
    t_nsum: 600
    t_nlost: 50

standard_star_params: 

calibrate_params: 
